name: smartCv_app
description: A Flutter app helps users smart cv app.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.9.0-0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & State
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  intl: any
  shared_preferences: ^2.3.5
  dotted_border: ^3.1.0
  # HTTP & JSON
  dio: ^5.7.0
  json_annotation: ^4.9.0
  file_picker: ^8.0.0
  http: ^1.2.0
  firebase_core: ^4.2.1
  firebase_auth: 6.1.2
  cloud_firestore: ^6.1.0
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.1.10
  flutter_pdfview: ^1.3.0
  path_provider: ^2.1.5
  open_file: ^3.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env

#  assets:
#    - assets/activities.json
#    - assets/destinations.json
#    - assets/logo.svg
#    - assets/user.jpg
